/* The following code was generated by JFlex 1.6.1 */

/*------------  1ra Area: Codigo de Usuario ---------*/
//------> Paquetes,importaciones
package scanner;
import java_cup.runtime.*;
import java.util.LinkedList;
import parser.Simbolos;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
/*------------  2da Area: Opciones y Declaraciones ---------*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>A_lexico.jflex</tt>
 */
public class Analizador_Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    10, 10, 10, 10, 10, 10, 10, 10, 10,  4,  2, 62,  4,  1, 10, 10, 
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  0,  0,  0,  0, 
     4, 38, 39, 40, 41, 42, 43, 44, 36, 37, 34, 32, 46, 33, 45, 35, 
     7,  5,  5,  5,  5,  5,  5,  5,  5,  5, 47,  3, 48, 49, 50, 51, 
     0, 15, 11, 20,  6, 14, 27, 30,  9, 26,  9, 19, 13, 31, 16, 12, 
    29,  9, 17, 24, 22, 21, 28,  9,  8,  9,  9, 57, 59, 58, 60, 61, 
    52, 15, 11, 20,  6, 14, 27, 30,  9, 26,  9, 19, 13, 31, 16, 12, 
    29,  9, 17, 24, 22, 21, 28,  9,  8,  9,  9, 53, 55, 54, 56, 10, 
    10, 10, 10, 10, 10, 63, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
     0,  0,  9,  9,  9,  9,  0,  0,  0,  0,  9,  0,  0, 10,  0,  0, 
     0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0, 
     9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 
     9,  9,  9,  9,  9,  9,  9,  0,  9,  9,  9,  9,  9,  9,  9,  9, 
     9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 
     9,  9,  9,  9,  9,  9,  9,  0,  9,  9,  9,  9,  9,  9,  9,  9
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\4\5\5"+
    "\1\1\5\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\2\0\10\5\1\0\1\44\1\5\1\44\5\5\1\45"+
    "\1\46\2\5\1\0\6\5\2\47\1\50\1\5\1\0"+
    "\2\5\1\0\3\5\2\51\2\5\1\0\2\5\1\52"+
    "\1\0\1\5\2\53\1\5\2\54\1\5\2\55\1\5"+
    "\1\0\1\5\2\56\1\5\2\57\2\5\1\60\1\0"+
    "\3\5\1\61\1\0\1\5\1\62\1\63\2\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\100\0\100\0\300\0\u0100\0\u0140"+
    "\0\u0180\0\u01c0\0\u0200\0\u0240\0\u0280\0\u02c0\0\u0300\0\u0340"+
    "\0\u0380\0\u03c0\0\u0400\0\100\0\100\0\100\0\u0440\0\100"+
    "\0\100\0\100\0\100\0\100\0\u0100\0\100\0\100\0\100"+
    "\0\100\0\100\0\100\0\100\0\100\0\100\0\100\0\100"+
    "\0\100\0\100\0\100\0\100\0\100\0\100\0\100\0\100"+
    "\0\u0100\0\u0480\0\u04c0\0\u0500\0\u0540\0\u0580\0\u05c0\0\u0600"+
    "\0\u0640\0\u0680\0\u06c0\0\u0700\0\100\0\u0740\0\u0100\0\u0780"+
    "\0\u07c0\0\u0800\0\u0840\0\u0880\0\100\0\u04c0\0\u08c0\0\u0900"+
    "\0\u0940\0\u0980\0\u09c0\0\u0a00\0\u0a40\0\u0a80\0\u0ac0\0\100"+
    "\0\u0100\0\u0100\0\u0b00\0\u0b40\0\u0b80\0\u0bc0\0\u0c00\0\u0c40"+
    "\0\u0c80\0\u0cc0\0\100\0\u0100\0\u0d00\0\u0d40\0\u0d80\0\u0dc0"+
    "\0\u0e00\0\u0100\0\u0e40\0\u0e80\0\100\0\u0100\0\u0ec0\0\100"+
    "\0\u0100\0\u0f00\0\100\0\u0100\0\u0f40\0\u0f80\0\u0fc0\0\100"+
    "\0\u0100\0\u1000\0\100\0\u0100\0\u1040\0\u1080\0\u0100\0\u10c0"+
    "\0\u1100\0\u1140\0\u1180\0\u0100\0\u11c0\0\u1200\0\u0100\0\u0100"+
    "\0\100\0\u0100";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\4\1\6\1\7\1\10"+
    "\2\7\1\2\1\11\2\7\1\12\2\7\1\13\1\2"+
    "\1\7\1\14\1\7\1\15\1\2\1\7\1\16\1\17"+
    "\1\20\1\21\1\22\1\7\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\104\0\1\62\102\0\1\6\1\0"+
    "\1\6\75\0\15\7\1\0\4\7\1\0\1\7\1\0"+
    "\6\7\11\0\1\7\23\0\1\7\1\0\1\7\5\0"+
    "\1\6\1\0\1\6\1\63\74\0\7\7\1\64\4\7"+
    "\1\65\1\0\4\7\1\0\1\7\1\0\6\7\11\0"+
    "\1\7\23\0\1\7\1\0\1\7\5\0\10\7\1\66"+
    "\4\7\1\0\4\7\1\0\1\7\1\0\6\7\11\0"+
    "\1\7\23\0\1\7\1\0\1\7\5\0\11\7\1\67"+
    "\3\7\1\0\4\7\1\0\1\7\1\0\6\7\11\0"+
    "\1\7\23\0\1\7\1\0\1\7\5\0\7\7\1\70"+
    "\1\71\1\7\1\72\2\7\1\0\4\7\1\0\1\7"+
    "\1\0\6\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\5\0\14\7\1\73\1\0\4\7\1\0\1\7\1\0"+
    "\6\7\11\0\1\7\23\0\1\7\1\0\1\7\20\0"+
    "\1\74\12\0\1\75\51\0\13\7\1\76\1\7\1\0"+
    "\4\7\1\0\1\7\1\0\1\7\1\77\4\7\11\0"+
    "\1\7\23\0\1\7\1\0\1\7\5\0\7\7\1\100"+
    "\2\7\1\101\2\7\1\0\4\7\1\0\1\7\1\0"+
    "\6\7\11\0\1\7\23\0\1\7\1\0\1\7\5\0"+
    "\7\7\1\102\5\7\1\0\4\7\1\0\1\7\1\0"+
    "\6\7\11\0\1\7\23\0\1\7\1\0\1\7\5\0"+
    "\14\7\1\103\1\0\4\7\1\0\1\7\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\5\0\12\7"+
    "\1\104\2\7\1\0\4\7\1\0\1\7\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\43\0\1\105"+
    "\37\0\1\4\101\0\3\106\3\0\1\106\2\0\2\106"+
    "\4\0\1\106\6\0\1\106\51\0\7\7\1\107\5\7"+
    "\1\0\4\7\1\0\1\7\1\0\6\7\11\0\1\7"+
    "\23\0\1\7\1\0\1\7\5\0\11\7\1\110\3\7"+
    "\1\0\4\7\1\0\1\7\1\0\6\7\11\0\1\7"+
    "\23\0\1\7\1\0\1\7\5\0\15\7\1\0\4\7"+
    "\1\111\1\112\1\0\6\7\11\0\1\7\23\0\1\7"+
    "\1\0\1\7\5\0\15\7\1\0\3\7\1\113\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\5\0\13\7\1\114\1\7\1\0\4\7\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\5\0\12\7\1\115\2\7\1\0\4\7\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\5\0\10\7\1\116\4\7\1\0\4\7\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\5\0\15\7\1\0\2\7\1\117\1\7\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\26\0\1\120\56\0\15\7\1\0\3\7\1\121"+
    "\1\0\1\7\1\0\6\7\11\0\1\7\23\0\1\7"+
    "\1\0\1\7\5\0\14\7\1\122\1\0\4\7\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\5\0\10\7\1\123\4\7\1\0\4\7\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\5\0\15\7\1\0\4\7\1\0\1\7\1\124"+
    "\1\125\5\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\5\0\7\7\1\126\5\7\1\0\4\7\1\0\1\7"+
    "\1\0\6\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\5\0\15\7\1\0\4\7\1\0\1\7\1\127\1\130"+
    "\5\7\11\0\1\7\23\0\1\7\1\0\1\7\5\0"+
    "\10\7\1\131\4\7\1\0\4\7\1\0\1\7\1\0"+
    "\6\7\11\0\1\7\23\0\1\7\1\0\1\7\5\0"+
    "\12\7\1\132\2\7\1\0\4\7\1\0\1\7\1\0"+
    "\6\7\11\0\1\7\23\0\1\7\1\0\1\7\16\0"+
    "\1\133\66\0\11\7\1\134\3\7\1\0\4\7\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\5\0\15\7\1\0\2\7\1\135\1\7\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\5\0\15\7\1\0\3\7\1\136\1\0\1\7"+
    "\1\0\6\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\5\0\15\7\1\0\4\7\1\137\1\140\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\5\0\10\7"+
    "\1\141\4\7\1\0\4\7\1\0\1\7\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\5\0\11\7"+
    "\1\142\3\7\1\0\4\7\1\0\1\7\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\5\0\15\7"+
    "\1\0\4\7\1\143\1\144\1\0\6\7\11\0\1\7"+
    "\23\0\1\7\1\0\1\7\6\0\1\145\76\0\1\7"+
    "\1\146\13\7\1\0\4\7\1\0\1\7\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\5\0\15\7"+
    "\1\0\4\7\1\0\1\7\1\0\4\7\1\147\1\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\20\0\1\150"+
    "\64\0\13\7\1\151\1\7\1\0\4\7\1\0\1\7"+
    "\1\0\6\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\5\0\11\7\1\152\3\7\1\0\4\7\1\0\1\7"+
    "\1\0\6\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\5\0\15\7\1\153\1\154\3\7\1\0\1\7\1\0"+
    "\6\7\11\0\1\7\23\0\1\7\1\0\1\7\5\0"+
    "\14\7\1\155\1\0\4\7\1\0\1\7\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\5\0\15\7"+
    "\1\0\4\7\1\0\1\7\1\156\1\157\5\7\11\0"+
    "\1\7\23\0\1\7\1\0\1\7\27\0\2\160\54\0"+
    "\15\7\1\0\4\7\1\160\1\161\1\0\6\7\11\0"+
    "\1\7\23\0\1\7\1\0\1\7\5\0\7\7\1\162"+
    "\5\7\1\0\4\7\1\0\1\7\1\0\6\7\11\0"+
    "\1\7\23\0\1\7\1\0\1\7\16\0\1\163\66\0"+
    "\11\7\1\164\3\7\1\0\4\7\1\0\1\7\1\0"+
    "\6\7\11\0\1\7\23\0\1\7\1\0\1\7\5\0"+
    "\14\7\1\165\1\0\4\7\1\0\1\7\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\5\0\12\7"+
    "\1\166\2\7\1\0\4\7\1\0\1\7\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\5\0\13\7"+
    "\1\167\1\7\1\0\4\7\1\0\1\7\1\0\6\7"+
    "\11\0\1\7\23\0\1\7\1\0\1\7\20\0\1\170"+
    "\64\0\13\7\1\171\1\7\1\0\4\7\1\0\1\7"+
    "\1\0\6\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\5\0\15\7\1\0\2\7\1\172\1\7\1\0\1\7"+
    "\1\0\6\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\5\0\12\7\1\173\2\7\1\0\4\7\1\0\1\7"+
    "\1\0\6\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\5\0\13\7\1\174\1\7\1\0\4\7\1\0\1\7"+
    "\1\0\6\7\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\25\0\1\175\57\0\15\7\1\0\2\7\1\176\1\7"+
    "\1\0\1\7\1\0\6\7\11\0\1\7\23\0\1\7"+
    "\1\0\1\7\5\0\15\7\1\0\3\7\1\177\1\0"+
    "\1\7\1\0\6\7\11\0\1\7\23\0\1\7\1\0"+
    "\1\7\5\0\15\7\1\0\4\7\1\0\1\7\1\0"+
    "\5\7\1\200\11\0\1\7\23\0\1\7\1\0\1\7"+
    "\16\0\1\201\66\0\11\7\1\202\3\7\1\0\4\7"+
    "\1\0\1\7\1\0\6\7\11\0\1\7\23\0\1\7"+
    "\1\0\1\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4672];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\2\11\16\1\3\11\1\1\5\11"+
    "\1\1\23\11\1\1\2\0\10\1\1\0\1\11\7\1"+
    "\1\11\3\1\1\0\6\1\1\11\3\1\1\0\2\1"+
    "\1\0\3\1\1\11\3\1\1\0\3\1\1\0\1\1"+
    "\1\11\2\1\1\11\2\1\1\11\2\1\1\0\1\1"+
    "\1\11\2\1\1\11\4\1\1\0\4\1\1\0\3\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //----> Codigo de usuario en sintaxis java
    public static LinkedList<TError> TablaEL = new LinkedList<TError>(); 

    //procedimiento que imprime el lexema en archivo
    public void imprimir(String argumento){
       BufferedWriter bw = null;
        FileWriter fw = null;
        try {

            File file = new File("D:\\Sexto Semestre\\Compiladores\\Compiler\\src\\scanner\\salida.txt");
            fw = new FileWriter(file.getAbsoluteFile(), true);
            bw = new BufferedWriter(fw);
            bw.write(argumento);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                            //Cierra instancias de FileWriter y BufferedWriter
                if (bw != null)
                    bw.close();
                if (fw != null)
                    fw.close();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
    public ArrayList<String> Tokens = new ArrayList<String>();
    public void enlistar(String argumento){
        Tokens.add(argumento);
    }
    


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador_Lexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { enlistar("ERROR LEXICO, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+" ");
        TError datos = new TError(yytext(),yyline,yycolumn,"Error Lexico","Simbolo no existe en el lenguaje");
        TablaEL.add(datos);
            }
          case 53: break;
          case 2: 
            { /*ignore*/
            }
          case 54: break;
          case 3: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.PC, yycolumn, yyline, yytext());
            }
          case 55: break;
          case 4: 
            { enlistar("Type: NUM, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+" "); return new Symbol(Simbolos.NUM, yycolumn, yyline, yytext());
            }
          case 56: break;
          case 5: 
            { enlistar("Type: ALPHA_NUM, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+" "); return new Symbol(Simbolos.alpha_num, yycolumn, yyline, yytext());
            }
          case 57: break;
          case 6: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.PLUS, yycolumn, yyline, yytext());
            }
          case 58: break;
          case 7: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.MINUS, yycolumn, yyline, yytext());
            }
          case 59: break;
          case 8: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.MORE, yycolumn, yyline, yytext());
            }
          case 60: break;
          case 9: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.DIV, yycolumn, yyline, yytext());
            }
          case 61: break;
          case 10: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.PARA, yycolumn, yyline, yytext());
            }
          case 62: break;
          case 11: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.PARC, yycolumn, yyline, yytext());
            }
          case 63: break;
          case 12: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.EXCLA, yycolumn, yyline, yytext());
            }
          case 64: break;
          case 13: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.QUOTE, yycolumn, yyline, yytext());
            }
          case 65: break;
          case 14: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.NUMERAL, yycolumn, yyline, yytext());
            }
          case 66: break;
          case 15: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.DOLAR, yycolumn, yyline, yytext());
            }
          case 67: break;
          case 16: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.PERCENT, yycolumn, yyline, yytext());
            }
          case 68: break;
          case 17: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.CAFE, yycolumn, yyline, yytext());
            }
          case 69: break;
          case 18: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.SINGLEQUOTE, yycolumn, yyline, yytext());
            }
          case 70: break;
          case 19: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.POINT, yycolumn, yyline, yytext());
            }
          case 71: break;
          case 20: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.COMMA, yycolumn, yyline, yytext());
            }
          case 72: break;
          case 21: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.DPOINT, yycolumn, yyline, yytext());
            }
          case 73: break;
          case 22: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.MINUS2, yycolumn, yyline, yytext());
            }
          case 74: break;
          case 23: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.EQUAL, yycolumn, yyline, yytext());
            }
          case 75: break;
          case 24: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.MINUS3, yycolumn, yyline, yytext());
            }
          case 76: break;
          case 25: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.INTER, yycolumn, yyline, yytext());
            }
          case 77: break;
          case 26: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.TILD, yycolumn, yyline, yytext());
            }
          case 78: break;
          case 27: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.LLAV, yycolumn, yyline, yytext());
            }
          case 79: break;
          case 28: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.LLAC, yycolumn, yyline, yytext());
            }
          case 80: break;
          case 29: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.OR, yycolumn, yyline, yytext());
            }
          case 81: break;
          case 30: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.EQUALS, yycolumn, yyline, yytext());
            }
          case 82: break;
          case 31: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.CORC, yycolumn, yyline, yytext());
            }
          case 83: break;
          case 32: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.CORD, yycolumn, yyline, yytext());
            }
          case 84: break;
          case 33: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.DIAGO, yycolumn, yyline, yytext());
            }
          case 85: break;
          case 34: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.EXP, yycolumn, yyline, yytext());
            }
          case 86: break;
          case 35: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.FLOOR, yycolumn, yyline, yytext());
            }
          case 87: break;
          case 36: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.IF, yycolumn, yyline, yytext());
            }
          case 88: break;
          case 37: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.COMMENT, yycolumn, yyline, yytext());
            }
          case 89: break;
          case 38: 
            { enlistar("Type: HEX, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+" "); return new Symbol(Simbolos.HEX, yycolumn, yyline, yytext());
            }
          case 90: break;
          case 39: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.INT, yycolumn, yyline, yytext());
            }
          case 91: break;
          case 40: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.FOR, yycolumn, yyline, yytext());
            }
          case 92: break;
          case 41: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.ELSE, yycolumn, yyline, yytext());
            }
          case 93: break;
          case 42: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.TRUE, yycolumn, yyline, yytext());
            }
          case 94: break;
          case 43: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.VOID, yycolumn, yyline, yytext());
            }
          case 95: break;
          case 44: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.MAIN, yycolumn, yyline, yytext());
            }
          case 96: break;
          case 45: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.BREAK, yycolumn, yyline, yytext());
            }
          case 97: break;
          case 46: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.CLASS, yycolumn, yyline, yytext());
            }
          case 98: break;
          case 47: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.FALSE, yycolumn, yyline, yytext());
            }
          case 99: break;
          case 48: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.RETURN, yycolumn, yyline, yytext());
            }
          case 100: break;
          case 49: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.BOOLEAN, yycolumn, yyline, yytext());
            }
          case 101: break;
          case 50: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.CALLOUT, yycolumn, yyline, yytext());
            }
          case 102: break;
          case 51: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.PROGRAM, yycolumn, yyline, yytext());
            }
          case 103: break;
          case 52: 
            { enlistar("Type: KW, Value: "+yytext()+", Column: "+yycolumn+", Line: "+yyline+""); return new Symbol(Simbolos.CONTINUE, yycolumn, yyline, yytext());
            }
          case 104: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
