
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package scanner;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int SPACE = 34;
  public static final int alpha_num = 51;
  public static final int EQUALS = 28;
  public static final int COMMENT = 6;
  public static final int CONTINUE = 39;
  public static final int PC = 19;
  public static final int INT = 44;
  public static final int HEX = 53;
  public static final int FOR = 42;
  public static final int MINUS = 3;
  public static final int FLOOR = 33;
  public static final int LLAV = 25;
  public static final int MINUS3 = 22;
  public static final int CALLOUT = 37;
  public static final int MINUS2 = 20;
  public static final int OR = 27;
  public static final int COMMA = 17;
  public static final int CLASS = 38;
  public static final int DIV = 5;
  public static final int CAFE = 14;
  public static final int NUM = 48;
  public static final int PLUS = 2;
  public static final int MAIN = 52;
  public static final int IF = 43;
  public static final int QUOTE = 10;
  public static final int SINGLEQUOTE = 15;
  public static final int EXP = 32;
  public static final int LLAC = 26;
  public static final int BOOLEAN = 35;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int TILD = 24;
  public static final int EQUAL = 21;
  public static final int TRUE = 46;
  public static final int PROGRAM = 50;
  public static final int error = 1;
  public static final int PERCENT = 13;
  public static final int BREAK = 36;
  public static final int VOID = 47;
  public static final int ELSE = 40;
  public static final int POINT = 16;
  public static final int NUMERAL = 11;
  public static final int DPOINT = 18;
  public static final int DIAGO = 31;
  public static final int PARC = 8;
  public static final int PARA = 7;
  public static final int CORD = 30;
  public static final int CORC = 29;
  public static final int FALSE = 41;
  public static final int INTER = 23;
  public static final int DOLAR = 12;
  public static final int ALPHA = 49;
  public static final int MORE = 4;
  public static final int EXCLA = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "MORE",
  "DIV",
  "COMMENT",
  "PARA",
  "PARC",
  "EXCLA",
  "QUOTE",
  "NUMERAL",
  "DOLAR",
  "PERCENT",
  "CAFE",
  "SINGLEQUOTE",
  "POINT",
  "COMMA",
  "DPOINT",
  "PC",
  "MINUS2",
  "EQUAL",
  "MINUS3",
  "INTER",
  "TILD",
  "LLAV",
  "LLAC",
  "OR",
  "EQUALS",
  "CORC",
  "CORD",
  "DIAGO",
  "EXP",
  "FLOOR",
  "SPACE",
  "BOOLEAN",
  "BREAK",
  "CALLOUT",
  "CLASS",
  "CONTINUE",
  "ELSE",
  "FALSE",
  "FOR",
  "IF",
  "INT",
  "RETURN",
  "TRUE",
  "VOID",
  "NUM",
  "ALPHA",
  "PROGRAM",
  "alpha_num",
  "MAIN",
  "HEX"
  };
}

